-- ID = CÓDIGO DE VERIFICAÇÃO
-- NM = NOME

CREATE TABLE CATEGORIA (
	ID_CATEGORIA INT(10) NOT NULL PRIMARY KEY,
    NM_CATEGORIA VARCHAR(50) NOT NULL
);

CREATE TABLE FABRICANTE (
	ID_FABRICANTE INT(10) NOT NULL PRIMARY KEY,
    NM_FABRICANTE VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUTO (
	ID_PRODUTO INT(10) NOT NULL PRIMARY KEY,
    NM_PRODUTO VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(200) NOT NULL,
	FK_CATEGORIA INT(10) NOT NULL,
    FK_FABRICANTE INT(10) NOT NULL,
    CONSTRAINT FK_CATEGORIA FOREIGN KEY (FK_CATEGORIA) REFERENCES CATEGORIA (ID_CATEGORIA),
    CONSTRAINT FK_FABRICANTE FOREIGN KEY (FK_FABRICANTE) REFERENCES FABRICANTE (ID_FABRICANTE)
);

CREATE TABLE FORNECEDOR (
	ID_FORNECEDOR INT(7) NOT NULL PRIMARY KEY,
    TELEFONE INT(11) NOT NULL,
    ENDERECO VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(45) NOT NULL
);

CREATE TABLE DISTRIBUIDOR (
	CNPJ INT(14) NOT NULL PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(100) NOT NULL,
    NM_FANTASMA VARCHAR(50) NOT NULL,
    FK_FORNECEDOR INT(7) NOT NULL,
    CONSTRAINT FK_FORNECEDOR FOREIGN KEY (FK_FORNECEDOR) REFERENCES FORNECEDOR (ID_FORNCEDOR)
);