DROP SCHEMA IF EXISTS HOTEL;
CREATE SCHEMA HOTEL;
USE HOTEL;

CREATE TABLE HOSPEDE (
	CODHOS INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMHOS VARCHAR (50) NOT NULL
);

CREATE TABLE EDIFICIO (
	CODEDI INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    NOMEDI VARCHAR(30) NOT NULL
);

CREATE TABLE QUARTO (
	CODQUA INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    NUMQUA INT NOT NULL, 
    CODEDI INT NOT NULL,
    CONSTRAINT FK_QUA_EDI FOREIGN KEY (CODEDI) REFERENCES EDIFICIO (CODEDI)
);

CREATE TABLE PROMOCAO (
	CODPRO INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    VLRPRO VARCHAR(30) NOT NULL
);

CREATE TABLE HOSPEDAGEM (
	CODHSP INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    PERHSP VARCHAR(30) NOT NULL, 
    CODHOS INT NOT NULL, 
    CODQUA INT NOT NULL, 
    CODPRO INT NOT NULL,
    CONSTRAINT FK_HSP_HOS FOREIGN KEY (CODHOS) REFERENCES HOSPEDE (CODHOS),
    CONSTRAINT FK_HSP_QUA FOREIGN KEY (CODQUA) REFERENCES QUARTO (CODQUA),
    CONSTRAINT FK_HSP_PRO FOREIGN KEY (CODPRO) REFERENCES PROMOCAO (CODPRO)
);

INSERT INTO HOSPEDE (NOMHOS) VALUES 
	('RAFAEL'),
	('FELIPE'),
	('RENATA'),
	('MARIA');

INSERT INTO EDIFICIO (NOMEDI) VALUES 
	('VENEZA'),
	('NAPOLI');

INSERT INTO QUARTO (NUMQUA, CODEDI) VALUES 
	(101, 1),
	(102, 1),
	(201, 1),
	(202, 1),
	(101, 2),
	(102, 2),
	(201, 2),
	(202, 2);

INSERT INTO PROMOCAO (VLRPRO) VALUES 
	('SEM DESCONTO'),
	('10% DE DESCONTO');

INSERT INTO HOSPEDAGEM (PERHSP, CODHOS, CODQUA, CODPRO) VALUES 
	('2 DIAS', 4, 2, 1),
	('3 DIAS', 3, 4, 2),
	('7 DIAS', 2, 1, 2),
	('1 DIA', 1, 7, 1);
    
-- a)   Mostrar todos os campos da tabela Hóspede.
	SELECT * FROM HOSPEDE;
    
-- b)   Mostrar o número de hospedagens que ocorreram.
	SELECT COUNT(CODHSP) FROM HOSPEDAGEM;
    
-- c)   Exibir as promoções sem as PKs.
	SELECT VLRPRO FROM PROMOCAO;
    
-- d)   Mostrar os quartos que pertencem ao edifício Veneza.
	SELECT * FROM QUARTO WHERE CODEDI = 1;
    
-- e)   Mostrar as hospedagens que foram pagas com desconto de 10%.
	SELECT *
	FROM HOSPEDAGEM
	INNER JOIN PROMOCAO ON HOSPEDAGEM.CODPRO = PROMOCAO.CODPRO
	WHERE PROMOCAO.VLRPRO = '10% DE DESCONTO';
    
-- f)    Mostrar os hóspedes que contenham a letra "E" no nome por ordem alfabética.
	SELECT *
	FROM HOSPEDE
	WHERE NOMHOS LIKE '%E%'
	ORDER BY NOMHOS ASC;
    
-- g)   Mostrar o tempo de duração das estadias com o nome dos hóspedes. 
	SELECT HOSPEDE.NOMHOS, HOSPEDAGEM.PERHSP
	FROM HOSPEDAGEM
	INNER JOIN HOSPEDE ON HOSPEDAGEM.CODHOS = HOSPEDE.CODHOS;
    
-- h)   Mostrar o nome dos Edifícios e os seus respectivos números de quartos.
	SELECT EDIFICIO.NOMEDI, QUARTO.NUMQUA
	FROM QUARTO
	INNER JOIN EDIFICIO ON QUARTO.CODEDI = EDIFICIO.CODEDI;

-- EDU
SELECT FUNCIONARIO.NOME, PROJETO.NM_PROJETO
FROM FUNCIONARIO
INNER JOIN PROJETO ON FUNCIONARIO.NOME = PROJETO.COD_PROJ WHERE PROJETO.COD_PROJ = 17;

SELECT F.NOME, P.NM_PROJ
FROM FUNCIONARIO, PROJETO
INNER JOIN FUNCIONARIO_PROJETO
ON F.MATRICULA = FUN.FK_MATRICULA,
P.COD_PROJ = FUN.P.COD_PROJ
WHERE NM_PROJ = "Delta"; 