DROP SCHEMA IF EXISTS HOTEL;
CREATE SCHEMA HOTEL;
USE HOTEL;

CREATE TABLE CARGO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO CARGO (NOME) VALUES
	('Programador'),
	('Projetista'),
    ('Analista');

SELECT * FROM CARGO ORDER BY NOME;